### PR TITLE
CSL-1722: Add hotkeys / keyboard shortcuts

### PR DESCRIPTION
**Pull request by mbrambilla**
Using: [hotkeys-js](https://github.com/jaywcjlove/hotkeys)

High priority items:
- [x] `alt+k` - Keyboard shortcut dialog
- [x] `alt+t` - TOC
- [x] `alt+h` - Highlights list
- [x] `alt+,` - Display settings
- [x] `alt+.` - Read-aloud settings (not listed in draft)
- [x] `alt+a` - Toggle Read-aloud Start/stop
- [x] `space` when reading - Read-aloud pause/resume
- [x] `alt+f` - Search input focus
- [x] `alt+r` - Reader content focus
- [x] `alt+l` - Library
- [ ] `alt+d` - Dashboard (not listed in draft)

Page navigation:
- ~~[ ] `left` - Previous screen (disabled until reader override available)~~
- ~~[ ] `right` - Next screen (disabled until reader override available)~~
- [x] `alt+pageup` - Previous chapter (reversed from draft)
- [x] `alt+pagedown` - Next chapter (reversed from draft)

Context menu: (only when selection within reading)
- [x] `alt+h` - Create highlight
- [x] `alt+d` - Word lookup (definition)
- [x] `alt+s` - Transform text (simplify)

Other :
- move focus to main navigation or create entry to each item in main nav?
  - wordbank?
  - manage page?
  - account/user menu?

Discussion posted in Slack also.

### CODE REVIEW

**Comment by mbrambilla** [comment]
Items in the header navigation, other than Library, will be handled through standard keyboard navigation and activation.  This can/will be revisited at a later time once user feedback is received.

**Comment by mbrambilla** [comment]
Placeholder dialog listing keyboard shortcuts added.  Will need review and some content updates.

**Comment by bgoldowsky** [comment]
With some font choices, the hot key styling merges together (Mac/FF):
image

Questions:
* Should we add left/right arrow to the keyboard shortcuts popup?
* How easy or hard would it be to detect Mac vs. other OS and avoid the need for the text at the top of that popup?

**Comment by mbrambilla** [comment]
- Added left/right to list
- Added some margin spacing for hotkey lists
- Conditional check to determine meta key based on OS
- Some stylelint fixes too

**Comment by bgoldowsky** [comment]
Looking really good.  Last change requests I promise.

I am testing all the events.  It seems like tts pause, resume, stop are all separately logged.  But 'play' is called 'hotkey-tts-toggle' - is that actually a toggle or can it be changed to hotkey-tts-play ?

Can we also change 'hotkey-settings-read-aloud' to 'hotkey-settings-reading-tools' -- and correspondingly the description in the popup to 'Show Reading tools settings' so it matches the title of that panel (which includes translation language as well).

**Pull request merged**
