### PR TITLE
Feature/CSL-1460 Implement customized vocabulary words for readings

### PR DESCRIPTION
**Pull request by klown**
Implement customized vocabulary words -- branch/PR for all [CSL-1460](https://castudl.atlassian.net/browse/CSL-1460) related tasks
- [x] Create database structure for vocabulary words ([CSL-1547](https://castudl.atlassian.net/browse/CSL-1547)),
- [ ] Add vocab word editing to customizations page ([CSL-1548](https://castudl.atlassian.net/browse/CSL-1548)),
- [ ] Make use of custom vocab words in choosing "Just right challenge" words and cued words ([CSL-1549](https://castudl.atlassian.net/browse/CSL-1549)).

### CODE REVIEW

**Comment by klown** [comment]
Added code for the second task, "Add vocab word editing to customizations page" ([CSL-1548](https://castudl.atlassian.net/browse/CSL-1548)).

The commit history is off, and this should be rebased/forked from head of the development branch.

**Comment by klown** [comment]
Closing -- replaced by the correct [PR#190](https://github.com/cast-org/clusive/pull/190)

**Comment by mbrambilla** [comment]
You should be able to [re-target PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) by using the 'edit' button next to the header.

**Comment by klown** [comment]
Thanks @mbrambilla! I'll keep that in mind for the next time.

**Pull request closed without merging**
